name: scraper

on:
  schedule:
  # Run at 5AM and 5PM UTC every day
    - cron: "0 5,17 * * *"
  workflow_dispatch:
  
jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1.3.4
      
      - name: Run scraper
        run: poetry install --no-root && poetry run python download.py

      - name: Update chart
        run: poetry run jupyter execute chart.ipynb
        
      - name: Add and commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          committer_name: Automated
          # The email of the custom committer you want to use
          committer_email: actions@users.noreply.github.com
          # The message for the commit
          message: "Latest data"
