name: scraper

on:
  schedule:
    - cron: "0 17 * * *" # 5PM UTC every day (10am SF)
  workflow_dispatch:
  
jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1.3.4
      
      - name: Run scraper
        run: poetry install && poetry run python download.py
        
      - name: Add and commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          committer_name: Automated
          # The email of the custom committer you want to use
          committer_email: actions@users.noreply.github.com
          # The message for the commit
          message: "Latest data"
