name: scraper

on:
  schedule:
    - cron: "0 17 * * *" # 5PM UTC every day (10am SF)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.11"
    - name: Poetry Install
    uses: knowsuchagency/poetry-install@v2
    with:
    # Have poetry create a virtualenv for the project on installation.
    create-virtualenv: true
    - name: Run scraper
      run: poetry run python download.py
          
    
      
      
          
          
